# Generated by Django 2.2.4 on 2019-08-23 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=150, verbose_name='Course')),
                ('institution', models.CharField(max_length=150, verbose_name='Institution')),
                ('url_institution', models.CharField(max_length=350, verbose_name='Link of Institution')),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='End Date')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Is Actual?')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('profession', models.CharField(max_length=200, verbose_name='Profession')),
                ('telephone', models.CharField(max_length=30, verbose_name='Telephone')),
                ('adress', models.CharField(max_length=250, verbose_name='Adress')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('hire_me', models.TextField(verbose_name='Why Hire Me?')),
                ('about', models.TextField()),
                ('skill_1', models.CharField(max_length=50, verbose_name='Professional Skill 1')),
                ('value_skill_1', models.IntegerField(default=0, verbose_name='% Of Skill 1')),
                ('skill_2', models.CharField(max_length=50, verbose_name='Professional Skill 2')),
                ('value_skill_2', models.IntegerField(default=0, verbose_name='% Of Skill 2')),
                ('skill_3', models.CharField(max_length=50, verbose_name='Professional Skill 3')),
                ('value_skill_3', models.IntegerField(default=0, verbose_name='% Of Skill 3')),
                ('skill_4', models.CharField(max_length=50, verbose_name='Professional Skill 4')),
                ('value_skill_4', models.IntegerField(default=0, verbose_name='% Of Skill 4')),
                ('skill_5', models.CharField(max_length=50, verbose_name='Professional Skill 5')),
                ('value_skill_5', models.IntegerField(default=0, verbose_name='% Of Skill 5')),
                ('skill_6', models.CharField(max_length=50, verbose_name='Professional Skill 6')),
                ('value_skill_6', models.IntegerField(default=0, verbose_name='% Of Skill 6')),
                ('picture', models.ImageField(blank=True, upload_to='profile/images', verbose_name='Your Piture')),
                ('url_instagram', models.CharField(blank=True, max_length=350, verbose_name='URL Instagram')),
                ('url_facebook', models.CharField(blank=True, max_length=350, verbose_name='URL Facebook')),
                ('url_linkedin', models.CharField(blank=True, max_length=350, verbose_name='URL LinkeIn')),
                ('url_twitter', models.CharField(blank=True, max_length=350, verbose_name='URL Twitter')),
                ('url_github', models.CharField(blank=True, max_length=350, verbose_name='URL GitHub')),
                ('url_cv', models.TextField(verbose_name='URL CV')),
                ('url_strengths', models.TextField(blank=True, verbose_name='URL Strengths')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('role', models.CharField(max_length=50, null=True, verbose_name='Role')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('testimonial', models.TextField(max_length=125)),
                ('review_picture', models.ImageField(blank=True, upload_to='review/images', verbose_name='Your Piture')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=150)),
                ('icon', models.CharField(max_length=25, verbose_name='Icon')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('knowledge', models.IntegerField(default=0, verbose_name='% Knowledge')),
                ('technical_skill', models.BooleanField(blank=True, default=False, verbose_name='Technical Skill')),
                ('visible', models.BooleanField(blank=True, default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('role_1', models.CharField(max_length=100, verbose_name='Role 1')),
                ('role_2', models.CharField(max_length=100, verbose_name='Role 2')),
                ('url_company', models.CharField(max_length=350, verbose_name='Link of Company')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='End Date')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Is Actual?')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('sub_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('text', models.TextField(verbose_name='Description')),
                ('cover_image', models.ImageField(upload_to='portfolio/images', verbose_name='Cover Image')),
                ('image_1', models.ImageField(blank=True, upload_to='portfolio/images', verbose_name='Image 1')),
                ('legenda_1', models.CharField(blank=True, max_length=250, verbose_name='Legenda 1')),
                ('image_2', models.ImageField(blank=True, upload_to='portfolio/images', verbose_name='Image 2')),
                ('legenda_2', models.CharField(blank=True, max_length=250, verbose_name='Legenda 2')),
                ('image_3', models.ImageField(blank=True, upload_to='portfolio/images', verbose_name='Image 3')),
                ('legenda_3', models.CharField(blank=True, max_length=250, verbose_name='Legenda 3')),
                ('url', models.CharField(blank=True, max_length=400, null=True, verbose_name='Url Project')),
                ('url_info', models.CharField(blank=True, max_length=30, null=True, verbose_name='Info Link')),
                ('visible', models.BooleanField(blank=True, default=True, verbose_name='Visible')),
                ('categories', models.ManyToManyField(to='myprofile.Category')),
                ('technologies', models.ManyToManyField(to='myprofile.Technology')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('sub_title', models.CharField(max_length=100, verbose_name='Sub Title')),
                ('description', models.TextField(max_length=400)),
                ('url', models.CharField(blank=True, max_length=350, null=True, verbose_name='Link of Project')),
                ('image', models.ImageField(blank=True, upload_to='project/images', verbose_name='Project ImageF')),
                ('testimonial_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Testimonial Name')),
                ('testimonial_text', models.TextField(blank=True, max_length=130, null=True)),
                ('testimonial_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Testimonial Role')),
                ('testimonial_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Testimonial Company')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.Category')),
            ],
            options={
                'verbose_name': 'Featured Project',
                'verbose_name_plural': 'Featured Projects',
                'ordering': ['-date'],
            },
        ),
    ]
