# Generated by Django 2.2.4 on 2019-08-06 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('sub_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub Title')),
                ('text', models.TextField()),
                ('image_1', models.ImageField(blank=True, upload_to='portfolio/images', verbose_name='Image 1')),
                ('image_2', models.ImageField(blank=True, upload_to='portfolio/images', verbose_name='Image 2')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Url Project')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.Category')),
                ('technologies', models.ManyToManyField(to='myprofile.Technology')),
            ],
        ),
    ]
