# Generated by Django 2.2.4 on 2019-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_auto_20190808_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='legenda_1',
            field=models.CharField(blank=True, max_length=250, verbose_name='Legenda 1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='legenda_2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Legenda 2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='legenda_3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Legenda 3'),
        ),
    ]
