# Generated by Django 2.2.4 on 2019-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_auto_20190808_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=30, verbose_name='Telephone')),
                ('adress', models.CharField(max_length=250, verbose_name='Adress')),
                ('about', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='profile/images', verbose_name='Your Piture')),
                ('url_facebook', models.CharField(blank=True, max_length=350, verbose_name='URL Facebook')),
                ('url_twitter', models.CharField(blank=True, max_length=350, verbose_name='URL Twitter')),
                ('url_instagram', models.CharField(blank=True, max_length=350, verbose_name='URL Instagram')),
                ('url_github', models.CharField(blank=True, max_length=350, verbose_name='URL GitHub')),
                ('url_linkedin', models.CharField(blank=True, max_length=350, verbose_name='URL LinkeIn')),
                ('url_cv', models.TextField(verbose_name='URL CV')),
                ('url_strengths', models.TextField(blank=True, verbose_name='URL Strengths')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['name'],
            },
        ),
    ]
