# Generated by Django 2.2.4 on 2019-08-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='null', max_length=200, verbose_name='Profession'),
            preserve_default=False,
        ),
    ]
