# Generated by Django 2.2.4 on 2019-08-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_profile_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=150, verbose_name='Course')),
                ('description', models.TextField()),
                ('period', models.DateField(verbose_name='Period')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('review', models.TextField()),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('review_picture', models.ImageField(blank=True, upload_to='review/images', verbose_name='Your Piture')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('role_1', models.CharField(max_length=150, verbose_name='Role 1')),
                ('role_2', models.CharField(max_length=150, verbose_name='Role 2')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('period', models.DateField(verbose_name='Period')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['profession'],
            },
        ),
    ]
