# Generated by Django 2.2.4 on 2019-08-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0009_auto_20190809_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(default='null', max_length=150, verbose_name='Institution'),
            preserve_default=False,
        ),
    ]
