# Generated by Django 2.2.4 on 2019-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0010_education_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='url_institution',
            field=models.CharField(default='null', max_length=350, verbose_name='Link of Institution'),
            preserve_default=False,
        ),
    ]
