# Generated by Django 2.2.4 on 2019-08-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0012_auto_20190810_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['start_date'], 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
    ]
