# Generated by Django 2.2.4 on 2019-08-10 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0014_auto_20190810_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='End Date'),
        ),
    ]
