# Generated by Django 2.2.4 on 2019-08-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0015_auto_20190810_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
    ]
