# Generated by Django 2.2.4 on 2019-08-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0016_auto_20190810_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='url_company',
            field=models.CharField(default='null', max_length=350, verbose_name='Link of Company'),
            preserve_default=False,
        ),
    ]
