# Generated by Django 2.2.4 on 2019-08-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0017_workexperience_url_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=100),
        ),
    ]
