# Generated by Django 2.2.4 on 2019-08-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0018_auto_20190811_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='testimonial',
        ),
    ]
