# Generated by Django 2.2.4 on 2019-08-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0021_auto_20190811_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='null', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
