# Generated by Django 2.2.4 on 2019-08-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0022_auto_20190811_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='category',
            new_name='categories',
        ),
    ]
