# Generated by Django 2.2.4 on 2019-08-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0023_auto_20190811_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('sub_title', models.CharField(max_length=100, verbose_name='Sub Title')),
                ('description', models.TextField(max_length=400)),
                ('url', models.CharField(blank=True, max_length=350, null=True, verbose_name='Link of Project')),
                ('image', models.ImageField(blank=True, upload_to='project/images', verbose_name='Project ImageF')),
                ('testimonial_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Testimonial Name')),
                ('testimonial_text', models.TextField(blank=True, max_length=130, null=True)),
                ('testimonial_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Testimonial Role')),
                ('testimonial_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Testimonial Company')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.Category')),
            ],
            options={
                'verbose_name': 'Featured Project',
                'verbose_name_plural': 'Featured Projects',
                'ordering': ['-date'],
            },
        ),
    ]
