# Generated by Django 2.2.4 on 2019-08-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0025_featuredproject_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=150)),
                ('icon', models.CharField(max_length=25, verbose_name='Icon')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['date'],
            },
        ),
    ]
