# Generated by Django 2.2.4 on 2019-08-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0026_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='knowledge',
            field=models.IntegerField(default=0, verbose_name='% Knowledge'),
        ),
        migrations.AddField(
            model_name='technology',
            name='technical_skill',
            field=models.BooleanField(blank=True, default=True, verbose_name='Technical Skill'),
        ),
    ]
