# Generated by Django 2.2.4 on 2019-08-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0027_auto_20190811_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='technical_skill',
            field=models.BooleanField(blank=True, default=False, verbose_name='Technical Skill'),
        ),
    ]
