# Generated by Django 2.2.4 on 2019-08-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0028_auto_20190811_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hire_me',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
