# Generated by Django 2.2.4 on 2019-08-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0030_auto_20190812_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill_1',
            field=models.CharField(default='null', max_length=250, verbose_name='Professional Skill 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_2',
            field=models.CharField(default='null', max_length=250, verbose_name='Professional Skill 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_3',
            field=models.CharField(default='null', max_length=250, verbose_name='Professional Skill 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_4',
            field=models.CharField(default='null', max_length=250, verbose_name='Professional Skill 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='value_skill_1',
            field=models.IntegerField(default=0, verbose_name='% Of Skill 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='value_skill_2',
            field=models.IntegerField(default=0, verbose_name='% Of Skill 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='value_skill_3',
            field=models.IntegerField(default=0, verbose_name='% Of Skill 3'),
        ),
        migrations.AddField(
            model_name='profile',
            name='value_skill_4',
            field=models.IntegerField(default=0, verbose_name='% Of Skill 4'),
        ),
    ]
