# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mycv.wsgi

beta_settings:
    cloud_sql_instances: myprofile-239501:us-central1:my-profiledb

runtime_config:
  python_version: 3
# [END runtime]